### ISSUE TITLE
Changing default bindings makes easy-move-resize stop working

### ISSUE THREAD

**Issue by oliverjensen-wk** [dmarcotte/easy-move-resize#24] opened 2017-06-30 18:53 UTC
On macOS Sierra (10.12.5), changing the default bindings in any way causes easy-move-resize to stop working. Even restoring the binding to the original (Cmd and Ctrl) by selecting the menu options does not restore functionality. Selecting "Reset to Defaults" restores functionality.

For example:

- Start program with default bindings, Cmd and Ctrl are enabled in the menu, moving works as expected
- Open the menu, select Shift to change the binding to Shift-Cmd-Ctrl, moving windows does not work with the new binding.
- Open the menu, unselect Shift to change the bindings back to Cmd-Ctrl, moving windows does not work.
- Open the menu, select "Reset to Defaults". Selected menu options do not change, but moving windows works again (using Cmd-Ctrl)

**Comment by dmarcotte** [comment] 2017-07-14 20:34
Thanks @oliverjensen-wk.  Will have a look at this soon.

**Comment by jonathanwalter** [comment] 2017-07-19 19:54
Just want to chime in and say I suffer from this bug too :( I'm also on Sierra 10.12.5.

And it's super laggy as well, the window moves far "behind" the cursor. Should I open a separate issue for that, maybe?

**Comment by dmarcotte** [comment] 2017-07-21 17:42
Alright, fix in progress for this, but in the meantime, here's some relief...

## Workaround:
- press "Reset to Defaults"
- deselect all key options
- select the desired key options
- your choice should now be respected

The root cause here is a flaw in how the preferences are stored/modifed from the default state of having nothing stored.  You can sanity check that the actual preferences match what the app menu shows by issuing the command `defaults read org.dmarcotte.Easy-Move-Resize ModifierFlags` in Terminal.

**Comment by dmarcotte** [comment] 2017-07-21 17:44
@jonathanwalter feel free to put details about the lag in https://github.com/dmarcotte/easy-move-resize/issues/26.

Some apps will be inherently laggy because they don't play too nice with the accessibly api, but the steps to reproduce in #26 make me think there may be some optimizations we can/should make for large and dense displays, so any extra info you've got would be welcome.

**Comment by jonathanwalter** [comment] 2017-07-21 21:49
Happy to report that the workaround for the bindings work for me! Thanks!

**Comment by kurtontheway** [comment] 2017-07-26 14:47
The workaround works for me too!! Thank you @dmarcotte !

**Comment by dmarcotte** [comment] 2017-08-29 00:30
Fixed in https://github.com/dmarcotte/easy-move-resize/pull/30.  Download the new release from https://github.com/dmarcotte/easy-move-resize/releases/tag/1.1.1

Thanks again all for both the bug report and the patience.  Please let me know if you see further issues!

**Closed by dmarcotte** 2017-08-29 00:30 UTC
