### ISSUE TITLE
Clicks not registering

### ISSUE THREAD

**Issue by cfp2000** [dmarcotte/easy-move-resize#34] opened 2017-11-08 09:06 UTC
Hi!

I really like what you guys are doing! I love the snappy performance in the latest release!

I'm experiencing problems with clicks not registering when I'm using it. So sometimes I have to double-click to get a single click.

As soon as I disable easy move resize the problem seems to go away. 

Anyone else having this problem?

**Comment by nottings** [comment] 2017-11-09 15:39
I am also having the same issue.  It was driving me bonkers until I realized easy-move-resize was causing the issue.

**Comment by cfp2000** [comment] 2017-11-10 08:59
I'm not 100% sure but it seems that the problem has disappeared. 

I use http://plentycom.jp/en/steermouse/ and when I changed a mouse setting the problem seemed to have stopped. 

This is the setting that I previously had set to **off**

![screen shot 2017-11-10 at 09 57 10](https://user-images.githubusercontent.com/7823236/32650338-b264053c-c5fd-11e7-8804-0635ccb270bb.png)

So maybe this issue should be closed.  ¯\_(ツ)_/¯

**Comment by cfp2000** [comment] 2017-11-10 09:21
I might have jumped the gun on declaring that this fixed my problem. 😞 

I'm still having problem with missed clicks. But maybe not as frequent.

**Comment by dmarcotte** [comment] 2017-11-16 22:10
@cfp2000 can you help me understand your issue better?  While you have the Easy Move+Resize modifier keys held down, your clicks are all hogged by Easy Move+Resize (i.e. they are not passed though to the underlying app or the OS).  This is by design since if you're clicking to initiate a move or a resize, you don't want the click registering with the underlying app.

Is that what you are seeing?  Or are you seeing other ignored clicks?  Thanks in advance for the help here.

**Comment by cfp2000** [comment] 2017-11-16 22:32
Great clarification! 

It's ignoring my normal clicks. Or it's actually ignoring one in every few clicks. I'm not pressing the modifier key. 

I was going nuts for a while. Changed my mouse. But later I had the same issue on my trackpad. And when I quit the easy resize app the problem went away. 

I haven't had this problem prior to the latest release.

**Comment by nottings** [comment] 2017-11-16 22:49
Since I'm experiencing the exact same issue, I will elaborate with the following thought.  If I take the time to make sure my mouse pointer comes to a complete stop and then carefully click without causing the pointer to move, my click seems to register every time.  If the pointer moves at all, the click only sometimes registers. I also do not use modifier keys.  Also, it seems to depend on what I am clicking.  For example, if I am clicking to move the carat within a body of text, it registers every time.  If I am clicking a button or hyperlink, the problems exists.

**Comment by dmarcotte** [comment] 2017-11-17 00:51
Thanks @cfp2000, @nottings.  Definitely want to get this fixed, but I'm having trouble reproducing which of course makes that difficult... will keep trying, but in the meantime, if you're able to zero in on a fairly reliable way to demonstrate this, that would be a huge help.

**Comment by nottings** [comment] 2017-11-17 18:17
I can't believe I didn't notice this before but, for me, it is only happening in Chrome browser.  Clicks work everywhere else just fine, including other browsers such as Firefox and Safari.
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
on macOS Sierra 10.12.6

**Comment by cfp2000** [comment] 2017-11-17 19:19
Hmm. I'm also using Chrome and High Sierra. 

I found the following:
- https://productforums.google.com/forum/#!topic/chrome/2s3ejYEm_QY
- https://github.com/fifafu/BetterTouchTool/issues/1445

And I think that i can replicate it on https://jsfiddle.net/xiel/wp8rggur/ 

Here is a gif of me replicating it:
![nov-17-2017 20-13-15](https://user-images.githubusercontent.com/7823236/32964777-961ee6d0-cbd4-11e7-8fb2-066c701e1193.gif)


I'm doing that on my High Sierra 10.13.1 + Chrome 62.0.3202.94 + trackpad on my macbook. 

The problem goes away if I disable Easy Move+Resize. 😃

**Comment by cfp2000** [comment] 2017-11-17 19:22
I can't replicate it on Google Canary 64.0.3271.0. 

I think we can close this issue.. 😃

**Comment by dmarcotte** [comment] 2017-11-17 19:48
Fantastic analysis @nottings, @cfp2000 (and great jsfiddle repro! Made it possible for me to see this problem in action).  I am indeed going to close this as it looks like Chrome is getting a fix in fairly quickly.

([This issue](https://github.com/fifafu/BetterTouchTool/issues/1445) that @cfp2000 linked to above contains a bunch more great context/info here, with [this comment in particular](https://github.com/fifafu/BetterTouchTool/issues/1445#issuecomment-330814807) bringing it all together).

Thanks again everyone!

**Closed by dmarcotte** 2017-11-17 19:48 UTC

**Comment by cfp2000** [comment] 2017-11-18 09:07
Nice! 👍 

(I found the jsfiddle on one of the pages so I can't take credit for it other than finding it 😉  )
