### ISSUE TITLE
crashes when used with gtk+ apps

### ISSUE THREAD

**Issue by xortim** [dmarcotte/easy-move-resize#6] opened 2014-06-18 12:14 UTC
The application crashes when attempting to move/resize a GTK+ app (such as Wireshark) but not on the native GTK+ apps like Gimp

**Comment by dmarcotte** [comment] 2017-08-29 00:33
Really looks like this is purely a limitation of the Accessibility API.  Since by design this app can do it thing if and only if that API supports it, I'm closing this out.

(Note that if someone's got evidence that the Accessibility API _does_ work for these apps and something in the implementation here is flawed, please do provide more info in an issue!)

**Closed by dmarcotte** 2017-08-29 00:33 UTC
