### ISSUE TITLE
MS Excel for Mac v16.16

### ISSUE THREAD

**Issue by arslanz** [dmarcotte/easy-move-resize#45] opened 2018-09-26 17:18 UTC
The app does not work at all within Excel for Mac - the resize and the move. I have tried numerous key combinations in the settings but none of them have any effect with Excel windows. I have tried with MS Outlook and MS Word - these apps work fine.

**Comment by dmarcotte** [comment] 2018-10-02 21:37
Thanks for the heads up here @arslanz.  What version of Excel are you using?

**Comment by arslanz** [comment] 2018-10-03 12:54
It's actually v16.16.2.

**Comment by dmarcotte** [comment] 2018-10-03 17:43
Thanks @arslanz.  I've installed v16.16.2 and confirmed the problem you're seeing.

Unfortunately, Easy Move+Resize _is_ working, but it appears Excel has implemented large portions of its UI in a way which is incompatible with the Apple Accessibility API (which this project depends on to do its thing).  You can see this by for instance using Easy Move+Resize on the ribbon or the bottom border of an Excel window: we can move and resize from there, but not anywhere in the main spreadsheet.

Going to close this as won't fix because as far as I know there's nothing we can do overcome Excel not properly supporting the API we rely on.

**Closed by dmarcotte** 2018-10-03 17:43 UTC
