### ISSUE TITLE
Command key is not handed down to application when clicking

### ISSUE THREAD

**Issue by j0ju** [dmarcotte/easy-move-resize#42] opened 2018-08-01 11:06 UTC
I tried using command key as move and resize modifier.
In some browsers (tested with Mozilla, Chrome, Safari) pressing CMD opens the Link in a new tab.
When the modifier is set to CMD only the click is not handed down to the application.
Dragging works as expected but not clicking while pressing CMD.

OsX 10.13.6
Easy-move-Resize: 1.2.0

**Comment by dmarcotte** [comment] 2018-10-03 17:55
@j0ju this is by design, and is indeed a bit of a pickle: if the click _is_ passed down to the application, then you would often be accidentally opening tabs when trying to move or resize.  But by not passing it down, if you've chosen CMD as your modifier, you cannot CMD-click for links at all any more.  (This is true of other modifiers too: for instance, there's some odd window-hiding behavior built into MacOS that hides the active window when you OPTION-click something else, so if you like that behavior, OPTION isn't a good modifier for Easy Move_Resize either)

A two-key combination is generally a better bet (and is why CMD-CTRL is the default here).  Closing this as won't fix, but I appreciate you reaching out about it.

**Closed by dmarcotte** 2018-10-03 17:55 UTC

**Comment by raphendyr** [comment] 2021-05-28 19:06
Sorry to raise more conversation about this, but I would like to use just the command as the modifier.

So, would it be problematic if this app would send "command + mouse press" and "command + mouse release" events, when the user releases the mouse button and the user didn't move the mouse (i.e., no dragging occurred). This way, if the user drags the window, the window in question wouldn't receive any events. However, if the user didn't move the mouse, then the events would be passed to the window, but would be delayed until the mouse button is released.

I find two conditions when the press and release events wouldn't be send to the window. First, if mouse is moved while the modifier and a mouse button is pressed. Second, if too much time passes while the modifier and a mouse button are held down (i.e., the mouse button press has to be a click type of event).

I have not read the code, so I don't even know if that would be hard or even impossible to implement.

**Comment by dmarcotte** [comment] 2021-06-03 00:04
Interesting idea, @raphendyr.  Whether we allow the event through is determined by whether [this method](https://github.com/dmarcotte/easy-move-resize/blob/main/easy-move-resize/EMRAppDelegate.m#L18) returns the event or `NULL`.  If you wanted to give a try at making this change and seeing how it feels, you may be able to update how that code decides between passing the event along or not.
